import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AntdRegistry from "./antd-registy";

const geistPoppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "3BRO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistPoppins.variable} antialiased `}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
